### ISSUE TITLE
No Checking of $page variable in header.inc.php

### ISSUE THREAD

**Issue by b00mhs99** [AusDTO/www.gov.au#1]
Severity:
Informational

Description:
Within the header.inc.php page the title of the page is derived from the $page variable that is set by the page that has included it. E.g 404.php If the header.inc.php page is called directly there is an error.

<b>Warning</b>:  main(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in <b>/app/web/docroot/www.gov.au/header.inc.php</b> on line <b>11</b><br />
<br />
<b>Notice</b>:  Undefined variable: pageTitle in <b>/app/web/docroot/www.gov.au/header.inc.php</b> on line <b>11</b><br />
- www.gov.au</title>

Mitigation:
Implement error checking to make sure the $page is set before the page is rendered.

**Comment by auxesis** [comment]
Fixing this by making the site entirely static.
